USE [master]
GO

/****** Object:  Database [Monitor]    Script Date: 11/3/2019 10:29:20 PM ******/
CREATE DATABASE [Monitor]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Monitor', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Monitor.mdf' , SIZE = 29696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Monitor_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Monitor_log.ldf' , SIZE = 353216KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Monitor] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Monitor].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Monitor] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Monitor] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Monitor] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Monitor] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Monitor] SET ARITHABORT OFF 
GO

ALTER DATABASE [Monitor] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Monitor] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Monitor] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Monitor] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Monitor] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Monitor] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Monitor] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Monitor] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Monitor] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Monitor] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Monitor] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Monitor] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Monitor] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Monitor] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Monitor] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Monitor] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Monitor] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Monitor] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Monitor] SET  MULTI_USER 
GO

ALTER DATABASE [Monitor] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Monitor] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Monitor] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Monitor] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Monitor] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Monitor] SET QUERY_STORE = OFF
GO

USE [Monitor]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Monitor] SET  READ_WRITE 
GO


